### ISSUE TITLE
Feature request: profiling of /debug/pprof endpoints

### ISSUE THREAD

**Issue by peterbourgon** [blainsmith/pprof.sh#1]
Nice!

The majority of the profiling I do is against /debug/pprof endpoints of running applications. It would be cool if this script supported that use case. Purely as an illustration and not at all as a suggested implementation, [capture-profiles.bash](https://gist.github.com/peterbourgon/2192a2265f6a8ea8871e06c1ae32b780) is a (redacted) version of a script I use for this purpose.

**Comment by blainsmith** [comment]
I like this idea and seems like a good addition to just profiling `Benchmark*` tests.

This script really lowered the bar for new Go devs to appreciate the profiling capabilities without having to remember tool's flags. If it can do the same for pulling in endpoints then I see it as a win.

**Comment by blainsmith** [comment]
This now supports the following and it will launch the visualizer after 10s:

```
> ./pprof.sh -b ./path/to/binary -u http://localhost:8080/debug/pprof/profile?seconds=10
```
